[general]
import = [
  "~/.config/alacritty/themes-toml/catppuccin_mocha.toml"
]

[font]
size = 14.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.85

[window.padding]
x = 20
y = 20
